---
dev_addr: "127.0.0.1:8001"
site_name: "Nautobot Ansible"
site_url: "https://nautobot-ansible.readthedocs.io"
repo_url: "https://github.com/nautobot/nautobot-ansible/"
edit_uri: blob/main/docs/
copyright: "Copyright &copy; The Authors"
docs_dir: docs

theme:
  name: material
  palette:
    - accent: deep orange
  features:
    - "content.code.copy"
    - "content.action.edit"
    - "content.action.view"
    - "navigation.expand"
    - "navigation.footer"
    - "navigation.instant"
    - "navigation.indexes"
    - "navigation.sections"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.tracking"
    - "search.highlight"
    - "search.share"
    - "search.suggest"
    - "toc.integrate"
extra:
  # TODO: Update these social items
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ansible-navigator/
      name: PyPI
    - icon: fontawesome/solid/scroll
      link: https://github.com/ansible/ansible-navigator/releases
      name: Releases
    - icon: simple/mastodon
      link: https://fosstodon.org/@ansible
      name: Mastodon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ansible
      name: Twitter
    - icon: simple/matrix
      link: https://matrix.to/#/#devtools:ansible.com
      name: Matrix
    - icon: fontawesome/solid/comments
      link: https://github.com/ansible/ansible-navigator/discussions
      name: Discussions
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ansible/ansible-navigator
      name: GitHub

watch:
  - README.md

nav:
  - Overview: "index.md"
  - Installation: "getting_started/installation.md"
  - User Guide & Module Reference:
    - Inventory Plugins:
      - GraphQL: "inventory/gql_inventory.md"
      - REST (Original): "inventory/inventory.md"
    - Lookup Plugins:
      - GraphQL: "lookup/lookup_graphql.md"
      - REST (Original): "lookup/lookup.md"
    - Module Plugins:
      - cable: "plugins/cable.md" 
      - circuit: "plugins/circuit.md"
      - circuit_termination: "plugins/circuit_termination.md"
      - circuit_type: "plugins/circuit_type.md"
      - cluster: "plugins/cluster.md"
      - cluster_group: "plugins/cluster_group.md"
      - cluster_type: "plugins/cluster_type.md"
      - console_port: "plugins/console_port.md"
      - console_port_template: "plugins/console_port_template.md"
      - console_server_port: "plugins/console_server_port.md"
      - console_server_port_template: "plugins/console_server_port_template.md"
      - contact: "plugins/contact.md"
      - controller: "plugins/controller.md"
      - custom_field: "plugins/custom_field.md"
      - custom_field_choice: "plugins/custom_field_choice.md"
      - device: "plugins/device.md"
      - device_bay: "plugins/device_bay.md"
      - device_bay_template: "plugins/device_bay_template.md"
      - device_interface: "plugins/device_interface.md"
      - device_interface_template: "plugins/device_interface_template.md"
      - device_redundancy_group: "plugins/device_redundancy_group.md"
      - device_type: "plugins/device_type.md"
      - front_port: "plugins/front_port.md"
      - front_port_template: "plugins/front_port_template.md"
      - inventory_item: "plugins/inventory_item.md"
      - ip_address: "plugins/ip_address.md"
      - ip_address_to_interface: "plugins/ip_address_to_interface.md"
      - location: "plugins/location.md"
      - location_type: "plugins/location_type.md"
      - manufacturer: "plugins/manufacturer.md"
      - namespace: "plugins/namespace.md"
      - nautobot_server: "plugins/nautobot_server.md"
      - platform: "plugins/platform.md"
      - plugin: "plugins/plugin.md"
      - power_feed: "plugins/power_feed.md"
      - power_outlet: "plugins/power_outlet.md"
      - power_outlet_template: "plugins/power_outlet_template.md"
      - power_panel: "plugins/power_panel.md"
      - power_port: "plugins/power_port.md"
      - power_port_template: "plugins/power_port_template.md"
      - prefix: "plugins/prefix.md"
      - provider: "plugins/provider.md"
      - query_graphql: "plugins/query_graphql.md"
      - rack: "plugins/rack.md"
      - rack_group: "plugins/rack_group.md"
      - rear_port: "plugins/rear_port.md"
      - rear_port_template: "plugins/rear_port_template.md"
      - relationship_association: "plugins/relationship_association.md"
      - rir: "plugins/rir.md"
      - role: "plugins/role.md"
      - route_target: "plugins/route_target.md"
      - service: "plugins/service.md"
      - status: "plugins/status.md"
      - tag: "plugins/tag.md"
      - team: "plugins/team.md"
      - tenant: "plugins/tenant.md"
      - tenant_group: "plugins/tenant_group.md"
      - virtual_chassis: "plugins/virtual_chassis.md"
      - virtual_machine: "plugins/virtual_machine.md"
      - vlan: "plugins/vlan.md"
      - vlan_group: "plugins/vlan_group.md"
      - vlan_location: "plugins/vlan_location.md"
      - vm_interface: "plugins/vm_interface.md"
      - vrf: "plugins/vrf.md"
    - Advanced Usage: "user_guide/advanced.md"
  - Developer Guide:
    - Code Reference:
      - Module Utils:
        - Circuits: "dev/code_reference/module_utils/circuits.md"
    - Contributing:
      - Documentation Generation: "dev/contributing/generate_docs.md"
      - New Releases: "dev/contributing/new_release.md"
      - Module Architecture: "dev/contributing/modules.md"
    - Code of Conduct: "dev/code_of_conduct.md"
    - Environment Variable Index: "dev/code_reference/environment_variables.md"
  - Release Notes:
      - ../code-of-conduct.md
      - contributing/security.md
      - contributing/guidelines.md

plugins:
  # - autorefs
  # - markdown-exec
  - material/search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # https://github.com/squidfunk/mkdocs-material/issues/6983
  # - material/social
  - material/tags
  # https://github.com/manuzhang/mkdocs-htmlproofer-plugin
  # - htmlproofer
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            merge_init_into_class: yes
            show_submodules: yes
            heading_level: 1
            show_root_heading: true
            show_root_members_full_path: true
            show_source: true
          import:
            - url: https://docs.ansible.com/ansible/latest/objects.inv
              domains: [py, std]

markdown_extensions:
  # - markdown_include.include:
  #     base_path: docs
  - "admonition"
  - "attr_list" # needed by our def_list use in order to add hrefs to <dt> tags
  - "def_list"
  - "footnotes"
  - "markdown_version_annotations"
  - "pymdownx.details"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.magiclink":
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - "pymdownx.tabbed":
      alternate_style: true
  - "toc":
      toc_depth: 2-3
      permalink: true
  - "pymdownx.superfences":
      "custom_fences":
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        # - name: python
        #   class: python
        #   validator: !!python/name:markdown_exec.validator
        #   format: !!python/name:markdown_exec.formatter