---
- name: INSTALL SYSTEM REQUIREMENTS
  ansible.builtin.apt:
    name:
      - git
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
    state: present
  tags: 
    - "nautobot"
